### ISSUE TITLE
Stopped working after .92

### ISSUE THREAD

**Issue by miraixyz** [custom-components/youtube#1]
**Version of the custom_component**

Current version?
**Describe the bug**
This has stopped working after .92

**log**
Integration youtube not found when trying to verify its sensor platform
```
Add your logs here.
```

Looks like this needs to be updated to work in the new custom components format

**Comment by Underknowledge** [comment]
Just create a empty `__init__.py` file in the directory  
https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html
