### ISSUE TITLE
Allow multiple sensors for multiple YouTube channels

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [custom-components/youtube#10]
**Is your feature request related to a problem? Please describe.**
Currently I can only get a single sensor to function. I would be great if this would allow me to create a sensor per YouTube channel.

**Describe the solution you'd like**
A sensor per YouTube channel.

**Describe alternatives you've considered**
I can't think of an alternative.

**Comment by ludeeus** [comment]
You can do that.

```
sensor youtube:
  - platform: youtube
    channel_id: UCZ2Ku6wrhdYDHCaBzLaA3bw
  - platform: youtube
    channel_id: UCZ2Ku6wrhdYDHCaBzLaA2bw
```
