### ISSUE TITLE
Duplicate url changes per new video - changing back to a previous upload url

### ISSUE THREAD

**Issue by gaussey** [custom-components/youtube#26]
**Version of the custom_component**

Latest
**Describe the bug**

I’m using this to notify me of when a new video is uploaded by certain channels, I’ve done some tests with my own channel and dummy uploads but the url changes to the last video uploaded and back again to the newest video, giving four repeat changes and therefore alerts per new video. This should be easy enough to replicate by uploading a dummy file to your own channel and watching the output in the entity in HomeAssistant.

**log**

```
Add your logs here.
```

**Comment by pinkywafer** [comment]
I've had this issue myself also for a long time now. I've been doing some testing, and I **may** have found a possible solution. Bear with me!
