### ISSUE TITLE
youtube redirect causes multiple attribute failures

### ISSUE THREAD

**Issue by craigmcgowan** [custom-components/youtube#31]
I've only recently found this component and am using 0.6.0 to feed in a few latest streams of a few favourite channels.

However, over the last couple of days I've noticed that "channel Image" has disappeared from all my sensors.

Anyone also having this issue?

**Comment by pinkywafer** [comment]
youtube is now redirecting any requests for a video or channel to a landing page warning about cookies.
This now causes ALL the following attributes to fail:
* stream
* live
* channel_is_live
* channel_image

**Comment by nytram-md** [comment]
Thanks for the update. Are we awaiting a fix or is this not possible ?

Thanks

Martyn

**Comment by pinkywafer** [comment]
I'm looking into it, but not sure as yet

**Comment by ludeeus** [comment]
I tried forcing the mobile site, but that was not stable

**Comment by pinkywafer** [comment]
no streaming / live etc data provided on the embed so cant use that either

**Comment by pinkywafer** [comment]
it seems that the consent page is bypassed if cookies are blocked... so is there any way to implement cookie blocking through the session we're using?

**Comment by nytram-md** [comment]
The guy who pointed this addon to me still has his working last weekend and he is on latest HA and 0.6.0, he lives in US and I live in UK. Could it be location issue ?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by pinkywafer** [comment]
that is a possibility, I believe the consent screen is related to Google's interpretation of the Europe wide GDPR.  However, the loaded page is specific to the location of the requesting client, so no easy way to load eg the USA version

**Comment by ludeeus** [comment]
We should not mess with the session.

The consent is probably only shown in countries covered by GDPR

**Comment by pinkywafer** [comment]
ok, I may be onto something... by sending a fake cookie with the request, we may be able to get around this.
can anyone please try the possible-fix-for-consent-screen branch?
