### ISSUE TITLE
Channels are not showing as live

### ISSUE THREAD

**Issue by nytram-md** [custom-components/youtube#32]
HACS add-on is not showing the YouTube when anyone is streaming live.

I'm on 2021.4.1

This has not worked since march update.2021.3

It worked great until then

**Comment by nytram-md** [comment]
This is this morning but it was like this all the way through Drzzs stream last night. I tried uninstalling 0.6.0 and reinstalling 0.5.0 but that didnt work and also didnt work still when I upgraded to 0.6.0 again

As you can see, the titles are updating, its just the "channel_is_live" is staying as false

![image](https://user-images.githubusercontent.com/55548608/116070681-d424af80-a684-11eb-9744-1599008b3582.png)

This is my sensor below.

![image](https://user-images.githubusercontent.com/55548608/116071058-45fcf900-a685-11eb-953b-b1eff4549752.png)

**Comment by nytram-md** [comment]
Any update or more information that I can send you ?

Thanks

Martyn

**Comment by pinkywafer** [comment]
ok, I've found the source of this (although not the solution).  it is the same issue which is causing #31 so closing this and continue there
