### ISSUE TITLE
play video, instead of showing the attributes?

### ISSUE THREAD

**Issue by rj-d2** [custom-components/youtube#33]
**Version of the custom_component**
0.6.0

**Describe the bug**
no bug,  just a question.

is it possible to start the latest video on click on the card, instead of showing the attributes?

**log**
Add your logs here.
no logs

**Comment by pinkywafer** [comment]
This is not possible in the integration.  There are various ways to play the video however, depending on how your front-end is setup.  you should be able to use the url as part of an action for any card type which supports this action, alternatively you can use the url in an automation (for example you can send a mobile app message to enable playing on the device by pressing the action)
