### ISSUE TITLE
Integration not working in Home Assistant 2021.7

### ISSUE THREAD

**Issue by sp7dpt** [custom-components/youtube#39]
**Version of the custom_component**
0.7.0

**Describe the bug**
sensor not present

**log**
no error log

**Comment by DavyRoswinkel** [comment]
Same problem here the sensors don't show up.

**Comment by DavyRoswinkel** [comment]
I searched in the old issues and I think it has something to do with Python 3.9. In Home Assistant 2021.6 Python 3.8 was used and is now updated to 3.9 in Home Assistant 2021.7
This issue is mentioned at https://github.com/custom-components/youtube/issues/16
Hope someone will find a solution.

**Comment by pinkywafer** [comment]
I've found the cause of the issue... fix coming shortly
