### ISSUE TITLE
2 Channels ? 

### ISSUE THREAD

**Issue by riotm0de** [custom-components/youtube#43]
**Version of the custom_component**
0.8.0 - latest HA (core-2021.8.8)

**Describe the bug**
as soon as i add a second channel_id it can't be parsed.

```
  - platform: youtube
    channel_id: XXXXXXX
    channel_id: XXXXXXX
```

**Comment by pinkywafer** [comment]
Ensure configuration is correct - see #27

**Comment by riotm0de** [comment]
ahh, thank you! maybe you add this information to the example.
