### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Krojack** [custom-components/youtube#47]
I installed via HACS and added everything but no entities show up. No errors in logs either, no nothing in the logs other than the "youtube which has not been tested by Home Assistant" warning at HA startup.

I'm just wondering if Google changed something breaking this. Doesn't look like any of the files have been updated in some time.

**Comment by gaussey** [comment]
Yup, still works.

![A2591604-C176-4BD1-85BD-8D9EF6694AF3](https://user-images.githubusercontent.com/1004313/143296916-00ffdfce-759b-4ebe-8113-066880697ede.jpeg)

**Comment by Krojack** [comment]
Weird... I'll try removing the HACS install and doing it manually and see if that does anything.

**Comment by gaussey** [comment]
Make sure you have added sensors into your configuration.yaml in this format
![8D85E98A-8130-4256-BC2A-E30B8FA67C69](https://user-images.githubusercontent.com/1004313/143297750-c410139e-41a6-4bd1-a70a-dad1e91dbbe9.png)

Then do a server restart.

Easiest way of testing is by adding your own channel and uploading a blank public video to check it picks it up. There is a delay…sometimes up to ten minutes before it does pick it up. It’s whenever YouTube adds the upload to the associated feed page.

**Comment by Krojack** [comment]
OH wow, I just found my oops.

In my configuration.yaml I use:
sensor:             !include_dir_merge_list configs/sensors/

But my 'youtube.yaml' file was up one directory... *facepalm*
