### ISSUE TITLE
Make last uploaded video a clickable link

### ISSUE THREAD

**Issue by allenrobberson** [custom-components/youtube#55]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I would like the last video uploaded link clickable, so when you click it in lovelace it will take you to the video

**Describe alternatives you've considered**
None

**Additional context**
I would like the link to be a highlighted and underlined link to the last available uploaded video to a channel.

**Comment by blackest** [comment]
you can have a notification message which performs like this you can probably modify the message e.g this automation action returns the url attribute as part of the message.  
service: persistent_notification.create
data:
  title: New Bearded Tinker Video
  message: latest Video {{ state_attr('sensor.beardedtinker', 'url') }}

**Comment by pinkywafer** [comment]
How are you displaying the link?  I believe this is a limitation of the card used. Depending on what card you use, it can be done in the card config.  If you open the entity, and the attributes, the link is 'clickable'.

**Comment by allenrobberson** [comment]
It was just displaying the link url text in the lovelace card. I can not show you at this time cause the YouTube intragrain is not working at this time.

**Comment by allenrobberson** [comment]
maybe the link could be added to a card like this:

`title: Weblinks
path: Weblinks
icon: mdi:web
cards:
  - type: entities
    title: HomeAssistant
    show_header_toggle: false
    entities:
      - type: weblink
        name: Home Assistant
        url: https://home-assistant.io
        icon: mdi:home-assistant`

**Comment by pinkywafer** [comment]
Closing as beyond the scope of an integration - this is dependent on choice of front end component
