### ISSUE TITLE
sensor not reporting any videos

### ISSUE THREAD

**Issue by daFreeMan** [custom-components/youtube#63]
**Version of the custom_component**
0.9.1

**Describe the bug**
I went to YouTube studio for my channel and from the URL `https:/studio.youtube.com/channel/<random string>` I pulled the `<random string>` and inserted it into my configuration.yaml:

```
sensor:
  - platform: youtube
    channel_id: UCrUdWfUN_UhhYNC0wQUFWyw
```
But it's not showing me any latest video. I know we streamed a video on 26 March.

In DevTools | Templates, I entered `{{ state_attr('sensor.youtube', 'stream') }}` and it reports `None`

I'm sure this is more of a user error than a bug - what am I doing wrong?

**log**
There is a warning about youtube not being approved (as there is for all HACS integrations), but otherwise there is nothing in the log itself about the youtube sensor.
[home-assistant_2023-03-31T20-51-30.353Z.log](https://github.com/custom-components/youtube/files/11126907/home-assistant_2023-03-31T20-51-30.353Z.log)

**Comment by pinkywafer** [comment]
Ok. First, did you restart home assistant after configuring?  It needs a full restart, not just a yaml reload.

Second.  The sensor will not be sensor.youtube, it will be sensor.<channel_name>

Third, check the channel_ID, I'd recommend using: https://www.streamweasels.com/tools/youtube-channel-id-and-user-id-convertor/

If still no good, can you give me the channel name, and I'll check here.

**Comment by daFreeMan** [comment]
Yes, I'd completely restarted HA several times.

It was the second point that was the problem. I was pretty certain it was user error, thanks for the correction. This makes _much_ more sense in being able to monitor multiple channels this way.
